import Head from 'next/head'
import Image from 'next/image'
import { CardContent, SectionContent } from '../src/core/constant/content'
const  NavBar = () => {
  const a_className = 'pl-5 pr-10 text-center h-8'
  const li_ClassName = 'inline-block'
  return (
    <div className='bg-black w-full h-10 items-center justify-around h-full w-full'>
      <ul className='py-4 inline-block justify-center items-center'>
        <li className={li_ClassName}>
        <a className={a_className}>TRANG CHỦ</a>
        </li >
        <li className={li_ClassName}>
        <a className={a_className}>SẢN PHẨM</a>
        </li>
        <li className={li_ClassName}>
        <a className={a_className}>GIỚI THIỆU</a>
        </li>
        <li className={li_ClassName}>
        <a className={a_className}>CHI TIẾT</a>
        </li>
        <li className={li_ClassName}>
        <a className={a_className}>LIÊN HỆ</a>
        </li>
      </ul>
    </div>
  )
}
  
const Card = ({img, title, content, isSection = false}) =>{
  const center = !isSection ? '' : 'text-center'
  return (
    <div className='grid grid-rows-2 m-2.5'>
      <div className={isSection ? 'm-auto' : ''}>
        <Image src={img} alt={title} />
      </div>
      <div className='mt-0'>
        <h1 className={`text-2xl mt-0 font-semibold ${center}`}>{title}</h1>
        <p className={`my-1 ${center}`}>{content}</p>
        {!isSection ? <button className='mt-1 bg-red-500 py-1 px-2 rounded-md text-white'>Chi tiết</button> : null }
      </div>
    </div>
  )
}


export default function Home() {
  const CardContents = CardContent
  const SectionContents = SectionContent
  return (
    <div className='mx-5 w-3/4' >
      <Head>
        <title>Interiror Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Image src={require('../img/LOGO.png')} alt="logo" />
        </div>
        <NavBar></NavBar>
        <div className='mt-4'>
          <Image src={require('../img/slider_1.png')} alt="slider_1" />
        </div>
        <div>
          <p>Tại <span className='font-bold text-red-600'>KLK PHUC THINH</span> vai trò thiết kế Kiến trúc nội thất của chúng tôi không đơn thuần chỉ là tạo nên không gian chức năng mà còn là nghệ thuật sáng tạo vận hành truyền cảm hứng đến người khác, đưa yếu tố con người hòa nhập với môi trường tự nhiên. Chúng tôi đầu tư nghiên cứu con người để biết lắng nghe cảm nhận, nhìn thấy điều mong muốn của bạn và đó là cách chúng tôi tôn trọng sự đam mê nghề nghiệp của chính mình.</p>
        </div>
        <div className='grid grid-cols-2 mt-4'>
          <div className='w-full grid-rows-2 pr-4'>
            <div className='grid grid-cols-2 pb-2'>
                <Image src={require('../img/img_nha_tam.jpg')} />
                <Image src={require('../img/sofa.jpg')}/>
            </div>
            <div>
              <Image src={require('../img/img_noi_that.jpg')}/>
            </div>
          </div>
          <div className='w-full pl-3'>
            <div className='w-full grid-rows-2'>
              <Image src={require('../img/img_phong_khach.jpg')}/>
              <Image src={require('../img/img_van_phong.jpg')}/>
            </div>
          </div>
        </div>
        <h1 className='text-center text-2xl	font-semibold'>CÁC SẢN PHẨM BÁN CHẠY</h1>
        <div className='grid grid-cols-4'>
          {
            CardContents.map(function(object, i){
              return <Card img={object.img} title={object.title} content={object.content} key={i} />
            })
          }
        </div>
        <div className='bg-naturebg bg-auto w-full h-[400px] py-20 pl-10'>
            <div className='text-center w-[225px] h-[225px] font-semibold text-white bg-red-500 rounded-full py-10 items-center opacity-70 items-center' >
              <h1 className='text-2xl'>SALE OFF</h1>
              <h1 className='text-5xl'>50%</h1>
              <p className='text-2xl'>Các loại sofa trong tháng 7</p>
            </div>
        </div>
        <div className=' grid grid-cols-3'>
          {
            SectionContents.map(function(object, i){
              return <Card img={object.img} title={object.title} content={object.content} isSection={true} key={i} />
            })
          }
        </div>
      </main>
      <footer className='bg-black w-full h-32 mb-5'>
        <div className='text-center text-white p-2.5'>
            <h1 className='text-2xl font-semibold'>Interiror Design</h1>
            <p>Địa chỉ: 225 đường Nguyễn Trải, P.4, Q.5. Tp HCM</p>
            <p>Điện thoại: (84) 39345678</p>
            <p>Điện thoại di động: (84) 39345678</p>
        </div>
      </footer>
    </div>
  )
}
